---
resources:
  - name: ets2_telemetry_mqtt
    type: git
    source:
      uri: https://github.com/balp/ets2_telemetry_mqtt.git
      branch: development

  - name: ets2_telemetry_mqtt-build-tools
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/ets2_telemetry_mqtt-build-tools

jobs:
  - name: publish
    public: true
    serial: true
    plan:
      - get: ets2_telemetry_mqtt
      - put: ets2_telemetry_mqtt-build-tools
        params:
          build: ets2_telemetry_mqtt/build-tools

  - name: job
    public: true
    plan:
      - in_parallel:
        - get: ets2_telemetry_mqtt-build-tools
        - get: ets2_telemetry_mqtt
          trigger: true
      - task: cmake-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((docker-hub-username))/ets2_telemetry_mqtt-build-tools
          inputs:
            - name: ets2_telemetry_mqtt
          outputs:
            - name: build_alpine_clang
          run:
            dir: build_alpine_clang
            path: cmake
            args: ["-G", "Ninja", "-D", "CMAKE_C_COMPILER=clang", "-D", "CMAKE_CXX_COMPILER=clang++", "-D",
                   "CMAKE_BUILD_TYPE=Release", "../ets2_telemetry_mqtt"]
          params:
            NAME: ((docker-hub-username))
      - task: cmake-build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((docker-hub-username))/ets2_telemetry_mqtt-build-tools
          inputs:
            - name: build_alpine_clang
            - name: ets2_telemetry_mqtt
          outputs:
            - name: build_alpine_clang
          run:
            dir: build_alpine_clang
            path: cmake
            args: ["--build", "."]
          params:
            NAME: ((docker-hub-username))
      - task: ctest
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((docker-hub-username))/ets2_telemetry_mqtt-build-tools
          inputs:
            - name: build_alpine_clang
          outputs:
            - name: build_alpine_clang
          run:
            dir: build_alpine_clang
            path: ctest
            args: ["."]
          params:
            NAME: ((docker-hub-username))
