---
resources:
  - name: ets2_telemetry_mqtt
    type: git
    source:
      uri: https://github.com/balp/ets2_telemetry_mqtt.git
      branch: development

  - name: ets2_telemetry_mqtt-build-tools
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/ets2_telemetry_mqtt-build-tools

jobs:
  - name: "publish build image"
    public: true
    serial: true
    plan:
      - get: ets2_telemetry_mqtt
        trigger: true
      - put: ets2_telemetry_mqtt-build-tools
        params:
          build: ets2_telemetry_mqtt/build-tools

  - name: "Linux plugin job"
    public: true
    plan:
      - in_parallel:
        - get: ets2_telemetry_mqtt-build-tools
          trigger: true
        - get: ets2_telemetry_mqtt
      - task: cmake-build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((docker-hub-username))/ets2_telemetry_mqtt-build-tools
          inputs:
            - name: ets2_telemetry_mqtt
          outputs:
            - name: build_alpine_clang
          run:
            dir: build_alpine_clang
            path: ../ets2_telemetry_mqtt/ci_build.sh
          params:
            NAME: ((docker-hub-username))
