---

platform: linux

image_resource:
  type: registry-image
  source:
    repository: balp/ets2_telemetry_mqtt-build-tools

inputs:
  - name: ets2_telemetry_mqtt

outputs:
  - name: html_docs
    path: build_alpine_clang/html

run:
  dir: build_alpine_clang
  path: "../ets2_telemetry_mqtt/tasks/ci_doc.sh"
  args: []

