---

platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((docker-hub-username))/ets2_telemetry_mqtt-build-tools

inputs:
  - name: ets2_telemetry_mqtt

outputs:
  - name: build_alpine_clang

run:
  dir: build_alpine_clang
  path: "../ets2_telemetry_mqtt/ci_build.sh"
  args: []

params:
  docker-hub-username: ((docker-hub-username))