FROM alpine:3.11.3
RUN apk add --no-cache \
        cmake \
        clang \
        compiler-rt \
        compiler-rt-static \
        git \
        ninja \
        binutils \
        build-base \
        openssh \
        openssl-dev \
        mosquitto-dev \
        graphviz \
        doxygen

